# Generated by Django 5.1.6 on 2025-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_registroasistencia_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='dependencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
