# Generated by Django 5.1.6 on 2025-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_registroasistencia_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
